### DISCUSSION TITLE
Compiling MAME with flatpak-builder makes my buildserver crash

### DISCUSSION THREAD

**Discussion by XargonWan** [mamedev/discussions#85] [Q&A]
Greetings,

I'm trying to compile MAME with flatpak-builder as you do in the original manifest, but it makes our buildserver crash after 50 minutes of compilation or such: the server just becomes unresponsive (even over ssh) and the build run fails.
Here is our [RetroDECK-MAME](https://github.com/XargonWan/RetroDECK-MAME) repo.

Our buildserver specs:

> CPU: Intel Xeon E3-1230v6 - 4c/8t - 3.5 GHz/3.9 GHz
> RAM: 16 GB ECC 2133 MHz

I tried to set a lower number of jobs, even tried with `-j 1` but it doesn´t seem to affect our issue.
Any help?

If you're wondering why it's not in the main RetroDECK manifest is because this issue and because MAME takes long to compile and a fresh compilation is not needed unless on version bump.

**Comment by startaq** [comment]
Well, any logs? 16 GB RAM should be okay for `-j 4`. Is there swap space on the server?

**Reply by rb6502** [reply]
Yeah, a log of the crash would be useful.  And build times don't *have* to be bad - I can do a clean full build of MAME in exactly 8 minutes on my new Apple M3 Max with -j16 and 64 GB of RAM.  I suspect the RAM helps more than the number of cores, because my 32 GB Ryzen 3900X is significantly slower.

**Reply by XargonWan** [reply]
How can I generate useful logs?
What I got from the GitHub Action Runner is just a truncated log where it's building until the server dies.

**Comment by galibert** [comment]
Please try compiling with clang and, importantly, linking with lld.  The memory usage is significantly lower and the link speed goes from tens of minutes to seconds.

**Reply by XargonWan** [reply]
I added the said lines but after 6h of compilation it just stopped.

```yml
  - name: mame
    buildsystem: simple
    build-options:
      no-debuginfo: true
      strip: true
      env:
        CC: clang
        CXX: clang++
        LD: lld
    build-commands:
      - make
          -j echo $(nproc)
          CFLAGS+=-Wno-error=restrict
          USE_QTDEBUG=0 
          USE_WAYLAND=1
          USE_SYSTEM_LIB_FLAC=1
          SDL_INI_PATH='$$HOME/.APP_NAME;/app/share/APP_NAME/ini'
          LDOPTS=-Wl,-s
     [...]
```

[Full manifest](https://github.com/XargonWan/RetroDECK-MAME/blob/main/net.retrodeck.mame.yml)

EDIT: now I tried to put that flags directly inside the make command unstead of the build-options.
